# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }


gem "sinatra", "~> 2.1"
gem "rack", "~> 2.2"

group :test do
    gem 'capybara'
    gem "rspec", "~> 3.9"
end




